Use "gender" as a stopword only when it's visible
glam-lab/degender-the-web pull request #90
Opened 2019-09-09 04:33 UTC by irhawk

Resolves #49.
@ProfJanetDavis If I should be handling the commit history differently – for example, if I should be squashing commits or something – please let me know!
Another area that may need attention is whether or not the tests have been implemented in the correct files.

2019-09-09 10:05 UTC, ProfJanetDavis commented on src/stopword-highlights.js
> +            // If any text node mentions gender,
I haven't seen this style of commenting on conditionals before. I like it.

2019-09-09 10:25 UTC, ProfJanetDavis requested changes
All my comments requiring changes are on the end-to-end test. You were right to be concerned about where you put things - I don't think the test is in the right place. It also needs clarification. You'll see my thought process in the comments.

There were a few things I decided not to comment on, where a moment's thought convinced me you made the right decision.

2019-09-09 10:25 UTC, ProfJanetDavis commented on src/stopword-highlights.js
> +    return false;
I haven't seen this style of commenting on conditionals before. I like it.

2019-09-09 10:25 UTC, ProfJanetDavis commented on test/e2e/content/case.nothing-to-change.test.js
>  });
This is confusing. The description is "it should make replacements", but the test is "expect(replacements).to.be.empty". Please clarify.

2019-09-09 10:25 UTC, ProfJanetDavis commented on test/e2e/content/case.nothing-to-change.test.js
>  });
Is a second test needed where pronouns are actually replaced? I'm fairly convinced this one test is adequate to ensure the right code path is being taken, but you should be convinced as well.

If you do think a second test is needed, that one would go in `test/e2e/content/case.with-gender-pronouns.test.js`

2019-09-09 10:25 UTC, ProfJanetDavis commented on test/e2e/content/case.nothing-to-change.test.js
>  });
If a single test, it is probably more appropriate to put it in a new file named something like `case.mentions-gender-invisibly.js`. The new test you wrote has no code in common with the existing tests in `case.nothing-to-change.test.js`, and I would argue it is actually a new use case. I don't mind proliferating files if it keeps the intention behind each file clearer.

2019-09-09 10:30 UTC, ProfJanetDavis commented
Also - yes, please do squash these commits! I'd like to see the tests and new code together in one commit. Ideally, you'd have written the tests before the code (see https://www.agilealliance.org/glossary/tdd/), though of course that wasn't possible here as I was still building out the test architecture.

2019-09-09 14:46 UTC, ProfJanetDavis commented on test/e2e/content/case.nothing-to-change.test.js
>  });
Or, perhaps better, all of the tests in his case could use the new page. The tests that were originally there would be equally applicable to the new page you created. You might rename it accordingly.

2019-09-11 08:05 UTC, irhawk commented
What do you think of including the link and hidden elements in `helper.html`? This ticket says that an invisible instance of the word "gender" should do nothing, so we might want to modify the page being tested rather than add new tests that mirror existing tests on a new page. Does that make sense?
One drawback of this option is that the messages shown for test failure won't say anything about hidden elements. That could make debugging more difficult.

2019-09-11 19:15 UTC, ProfJanetDavis commented
I like the idea of not proliferating HTML pages for testing. Yes, go ahead and do that.

2019-09-12 07:19 UTC, irhawk commented
I did a force-push because I mistakenly reset some changes. I hope to avoid that in the future by being more mindful of the remote.
This last commit was easier than writing new end-to-end tests, and it should either address or make irrelevant each of the comments above. Let me know if this needs anything else!

2019-09-12 12:09 UTC, ProfJanetDavis approved these changes
Looks good! Agreed, this is much simpler.

2019-09-12 12:10 UTC, merged